name: Build and Scan Multiple Images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.collect.outputs.images }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: asraf344
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all service images
        run: |
          VERSION=${GITHUB_REF_NAME}   # e.g., v1.2.3
          REPO="ghcr.io/${{github.repository}}"
          IMAGES=""

          for service in alpine-secret node-nodemon ubuntu-cpufetch; do
            DIR="image-builds/${service}"
            if [ -f "${DIR}/Dockerfile" ]; then
              IMAGE="${REPO}/${service}:${VERSION}"
              echo "🚀 Building $IMAGE"
              docker buildx build \
                --platform linux/amd64 \
                --tag "$IMAGE" \
                -f "${DIR}/Dockerfile" "${DIR}" \
                --push
              IMAGES="$IMAGES $IMAGE"
            fi
          done

          echo "Built images: $IMAGES"
          echo "IMAGES=$IMAGES" >> "$GITHUB_ENV"

      - name: Collect outputs
        id: collect
        run: |
          echo "images=${{ env.IMAGES }}" >> "$GITHUB_OUTPUT"

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: asraf344
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run conscan on built images
        run: |
          IMAGES="${{needs.build.outputs.images}}"
          echo "🧠 Scanning images: $IMAGES"
          mkdir -p reports cache
          chmod 777 reports cache

          for IMG in $IMAGES; do
            NAME=$(basename "$IMG" | cut -d: -f1)
            TAG=$(basename "$IMG" | cut -d: -f2)
            ReportDir="reports/$NAME"
            mkdir -p $ReportDir
            chmod 777 $ReportDir

            TAG=$(basename "$IMG" | cut -d: -f2)
            ReportDir="reports/$NAME"
            mkdir -p $ReportDir
            chmod 777 $ReportDir

            echo "🔍 Scanning $IMG ..."
            docker run --rm \
              -v "$HOME/.docker/config.json":/.docker/config.json \
              -v "$(pwd)/$ReportDir:/reports" \
              -v "$(pwd)/$ReportDir:/reports" \
              -v "$(pwd)/cache:/.cache" \
              ghcr.io/peek8/conscan \
              scan "$IMG" \
              --format html \
              --output "/reports/${TAG}.html"
              --output "/reports/${TAG}.html"
          done
          ls -l reports/
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: reports/
          retention-days: 1  
      
    
  update-index:
    runs-on: ubuntu-latest
    permissions:
      # for pushing/tagging
      contents: write
      # for pushing container images
      packages: write
    needs: scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout gh-pages
        run: |
          git fetch origin gh-pages || true
          git checkout -B gh-pages origin/gh-pages || git checkout --orphan gh-pages

      - name: Download reports artifact
        uses: actions/download-artifact@v4
        with:
          name: scan-reports
          path: reports/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Inject report links into index.html
        working-directory: ./gh-pages
        run: |
          npm install nunjucks
          mkdir -p reports # first time create dir
          
          echo "pwd $(pwd) list"
          ls -al $(pwd)
          echo "GITHUB_WORKSPACE :: $GITHUB_WORKSPACE list files:"
          ls -al $GITHUB_WORKSPACE

          echo "GITHUB_WORKSPACE report list:"
          ls -al $GITHUB_WORKSPACE/reports

          cp -r $GITHUB_WORKSPACE/reports/* reports/
          node update-report-index.js

      - name: Commit updated HTML
        run: |
          git config --global user.name "conscan[bot]"
          git config --global user.email "conscan[bot]@users.noreply.github.com"

          git add ./gh-pages/reports/*
          git commit -m "Update report index" || echo "No changes to commit"
          git push origin gh-pages